sudo: required

services:
  - docker

language: generic

before_script:
  - docker-compose build
  - docker-compose up
  - docker-compose run imical bundle exec rails db:test:prepare
script:
  - docker-compose run --rm imical bundle exec rake spec
