sudo: required
language: generic
services:
- docker
before_script:
- sudo /etc/init.d/postgresql stop
- docker-compose build
- docker-compose run imical bundle exec rails db:test:prepare
script:
- docker-compose run --rm imical bundle exec rake spec
