version: '3'
services:
  db:
    image: postgres
#    ports:
#      - 5432:5432
  imical:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/imical
    ports:
      - "3001:3000"
    depends_on:
      - db
