default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
<% if ENV['IMICAL_ENV'] == "docker" %>
  host: db
<% else %>
  host: localhost
<% end %>
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: imical_development


test:
  <<: *default
  database: imical_test
