<% if ENV['IMICAL_ENV'] == "docker" %>

default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost

  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: imical_development

test:
  <<: *default
  database: imical_test


<% else %>

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

<% end %>
