default: &default
  adapter: postgresql
  encoding: unicode
  # host: localhost
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: imical_development


test:
  <<: *default
  database: imical_test
